//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.DBServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBServiceReference.IDataBaseOperator")]
    public interface IDataBaseOperator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBaseOperator/Login", ReplyAction="http://tempuri.org/IDataBaseOperator/LoginResponse")]
        bool Login(string Nickname, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBaseOperator/Login", ReplyAction="http://tempuri.org/IDataBaseOperator/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string Nickname, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBaseOperator/Registration", ReplyAction="http://tempuri.org/IDataBaseOperator/RegistrationResponse")]
        bool Registration(string Nickname, string Password, string Fname, string Sname, string Mail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataBaseOperator/Registration", ReplyAction="http://tempuri.org/IDataBaseOperator/RegistrationResponse")]
        System.Threading.Tasks.Task<bool> RegistrationAsync(string Nickname, string Password, string Fname, string Sname, string Mail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataBaseOperatorChannel : Diploma.DBServiceReference.IDataBaseOperator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataBaseOperatorClient : System.ServiceModel.ClientBase<Diploma.DBServiceReference.IDataBaseOperator>, Diploma.DBServiceReference.IDataBaseOperator {
        
        public DataBaseOperatorClient() {
        }
        
        public DataBaseOperatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataBaseOperatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseOperatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataBaseOperatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string Nickname, string Password) {
            return base.Channel.Login(Nickname, Password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string Nickname, string Password) {
            return base.Channel.LoginAsync(Nickname, Password);
        }
        
        public bool Registration(string Nickname, string Password, string Fname, string Sname, string Mail) {
            return base.Channel.Registration(Nickname, Password, Fname, Sname, Mail);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrationAsync(string Nickname, string Password, string Fname, string Sname, string Mail) {
            return base.Channel.RegistrationAsync(Nickname, Password, Fname, Sname, Mail);
        }
    }
}
